// Styles
import "@/styles/globals.css";

// Providers
import { Providers } from "./providers";
import { Layout } from "@/components";

// Meta Tags
export const metadata = {
  title: "NextJs Starter",
  description: "Generated by @fek",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <body>
        <Providers>
          <Layout>{children}</Layout>
        </Providers>
      </body>
    </html>
  );
}
